Feature: evolve method
ogajduse/robocode-genetic-algorithms pull request #1
Opened 2018-11-11 20:12 UTC by sarkaaa

Napsali jsme metodu `evolve`, pochopili jsme více princip GA, refaktorovali jsme `getGenes` na `getGene` (dává to více smysl, jelikož vybíráme jen jeden gen). Dále jsme přidali getter a setter pro `fitness` a vytvořili jsme metodu pro výběr náhodného chromozomu `getRandomChromosome`. Review pls. :+1:

2018-11-11 22:01 UTC, rligocki reviewed
Zmena fitnes hodnoty na double OK 
GetGene ... Super napad OK 
GetFitness OK
setFitness OK

2018-11-11 22:02 UTC, rligocki requested changes
Evolve .. nemuze fungovat. Je potreba nejprve vypocitat fitness pro kazdy chromozome. Nasledne je seradit a potom je možné provést tento postup. Navrhuji ve funci evolve naimplementvoat treeset, do které se nakopírují aktuální chromozomy. POkud bude naimplementovano comparable pro chromozome tak dojde k automatickému seřazení a následně je možné vytahovat postupně jednotlivé chromozomý a dělat s nima evoluci.

2018-11-13 22:07 UTC, sarkaaa commented
@rligocki Opraveno. Pls review.
Misto Vectoru je TreeSet. Comparable implementovano. Fitness se prepocitava po kazdem cyklu a znovu se utvari strom, aby byl serazeny. 
Ukazkovy vystup, kdy se supertank vytvoril jiz v 5 generaci:
```
Generation: 0. Fitness of the first chromosome: 0.0
Generation: 0. Fitness of the second chromosome: 0.0
Generation: 1. Fitness of the first chromosome: 0.4934041303831571
Generation: 1. Fitness of the second chromosome: 0.5696036266505087
Generation: 2. Fitness of the first chromosome: 0.4934041303831571
Generation: 2. Fitness of the second chromosome: 0.5696036266505087
Generation: 3. Fitness of the first chromosome: 0.4934041303831571
Generation: 3. Fitness of the second chromosome: 0.5696036266505087
Generation: 4. Fitness of the first chromosome: 0.0
Generation: 4. Fitness of the second chromosome: 0.4934041303831571
```

To se ale muze taky stat v 34 generaci.
```
Generation: 0. Fitness of the first chromosome: 0.0
Generation: 0. Fitness of the second chromosome: 0.0
Generation: 1. Fitness of the first chromosome: 1.307987473134476
Generation: 1. Fitness of the second chromosome: 2.013221191496104
Generation: 2. Fitness of the first chromosome: 1.307987473134476
Generation: 2. Fitness of the second chromosome: 1.3315686576814703
Generation: 3. Fitness of the first chromosome: 1.307987473134476
Generation: 3. Fitness of the second chromosome: 1.3315686576814703
Generation: 4. Fitness of the first chromosome: 1.1726122182079253
Generation: 4. Fitness of the second chromosome: 1.296239141201598
Generation: 5. Fitness of the first chromosome: 1.1185049447279856
Generation: 5. Fitness of the second chromosome: 1.1726122182079253
Generation: 6. Fitness of the first chromosome: 1.1185049447279856
Generation: 6. Fitness of the second chromosome: 1.1726122182079253
Generation: 7. Fitness of the first chromosome: 0.49566780105337127
Generation: 7. Fitness of the second chromosome: 1.1185049447279856
Generation: 8. Fitness of the first chromosome: 0.49566780105337127
Generation: 8. Fitness of the second chromosome: 0.936121698179591
Generation: 9. Fitness of the first chromosome: 0.49566780105337127
Generation: 9. Fitness of the second chromosome: 0.936121698179591
Generation: 10. Fitness of the first chromosome: 0.027610272364647526
Generation: 10. Fitness of the second chromosome: 0.49566780105337127
Generation: 11. Fitness of the first chromosome: 0.027610272364647526
Generation: 11. Fitness of the second chromosome: 0.49566780105337127
Generation: 12. Fitness of the first chromosome: 0.027610272364647526
Generation: 12. Fitness of the second chromosome: 0.49566780105337127
Generation: 13. Fitness of the first chromosome: 0.027610272364647526
Generation: 13. Fitness of the second chromosome: 0.49566780105337127
Generation: 14. Fitness of the first chromosome: 0.027610272364647526
Generation: 14. Fitness of the second chromosome: 0.06384124134505986
Generation: 15. Fitness of the first chromosome: 0.027610272364647526
Generation: 15. Fitness of the second chromosome: 0.06384124134505986
Generation: 16. Fitness of the first chromosome: 0.027610272364647526
Generation: 16. Fitness of the second chromosome: 0.06384124134505986
Generation: 17. Fitness of the first chromosome: 0.027610272364647526
Generation: 17. Fitness of the second chromosome: 0.06384124134505986
Generation: 18. Fitness of the first chromosome: 0.027610272364647526
Generation: 18. Fitness of the second chromosome: 0.06384124134505986
Generation: 19. Fitness of the first chromosome: 0.027610272364647526
Generation: 19. Fitness of the second chromosome: 0.06301798591587127
Generation: 20. Fitness of the first chromosome: 0.027610272364647526
Generation: 20. Fitness of the second chromosome: 0.06301798591587127
Generation: 21. Fitness of the first chromosome: 0.027610272364647526
Generation: 21. Fitness of the second chromosome: 0.06301798591587127
Generation: 22. Fitness of the first chromosome: 0.027610272364647526
Generation: 22. Fitness of the second chromosome: 0.06301798591587127
Generation: 23. Fitness of the first chromosome: 0.027610272364647526
Generation: 23. Fitness of the second chromosome: 0.06301798591587127
Generation: 24. Fitness of the first chromosome: 0.027610272364647526
Generation: 24. Fitness of the second chromosome: 0.06301798591587127
Generation: 25. Fitness of the first chromosome: 0.027610272364647526
Generation: 25. Fitness of the second chromosome: 0.06301798591587127
Generation: 26. Fitness of the first chromosome: 0.027610272364647526
Generation: 26. Fitness of the second chromosome: 0.0334684461698207
Generation: 27. Fitness of the first chromosome: 0.027610272364647526
Generation: 27. Fitness of the second chromosome: 0.0334684461698207
Generation: 28. Fitness of the first chromosome: 0.027610272364647526
Generation: 28. Fitness of the second chromosome: 0.0334684461698207
Generation: 29. Fitness of the first chromosome: 0.027610272364647526
Generation: 29. Fitness of the second chromosome: 0.0334684461698207
Generation: 30. Fitness of the first chromosome: 0.027610272364647526
Generation: 30. Fitness of the second chromosome: 0.0334684461698207
Generation: 31. Fitness of the first chromosome: 0.027610272364647526
Generation: 31. Fitness of the second chromosome: 0.0334684461698207
Generation: 32. Fitness of the first chromosome: 0.027610272364647526
Generation: 32. Fitness of the second chromosome: 0.0334684461698207
Generation: 33. Fitness of the first chromosome: 0.0
Generation: 33. Fitness of the second chromosome: 0.027610272364647526
```

2018-11-14 21:24 UTC, ogajduse commented
Dnes jsme si rekli jake zmeny provedeme. Soucasny stav bych commitnul, mergnul a dalsi PR bych stavel na tomto.

2018-11-14 21:24 UTC, ogajduse approved these changes

2018-11-14 21:25 UTC, merged